import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format, eachDayOfInterval, getDay } from 'date-fns';
import type {
  AttendanceSheetParams,
  AttendanceRecord,
  RouteSheetData,
  EventRouteSheet,
} from '@/types';

const DAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

export class PDFGenerator {
  // ==================== ATTENDANCE SHEET ====================
  
  static generateAttendanceSheet(
    params: AttendanceSheetParams,
    busDetails: any,
    students: AttendanceRecord[]
  ): jsPDF {
    const doc = new jsPDF('l', 'mm', 'a4'); // Landscape orientation
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    
    // Header
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('SHANTINIKETAN INDIAN SCHOOL', pageWidth / 2, 15, { align: 'center' });
    
    doc.setFontSize(14);
    doc.text('TRANSPORT ATTENDANCE', pageWidth / 2, 22, { align: 'center' });
    
    // Bus Details
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    const leftMargin = 14;
    let yPos = 32;
    
    doc.text(`Route: ${busDetails.routeName}`, leftMargin, yPos);
    doc.text(`Bus Number: ${params.busNumber}`, leftMargin + 100, yPos);
    doc.text(`${params.shift}`, pageWidth - 30, yPos);
    
    yPos += 6;
    doc.text(`Driver Name: ${busDetails.driverName} - ${busDetails.driverContact}`, leftMargin, yPos);
    
    yPos += 6;
    doc.text(`Conductor Name: ${busDetails.conductorName} - ${busDetails.conductorContact}`, leftMargin, yPos);
    
    yPos += 6;
    const startDate = format(new Date(params.startDate), 'dd-MMM');
    const endDate = format(new Date(params.endDate), 'dd-MMM');
    doc.text(`DATE: ${startDate} to ${endDate}`, leftMargin, yPos);
    
    // Generate date columns
    const dates = eachDayOfInterval({
      start: new Date(params.startDate),
      end: new Date(params.endDate),
    }).filter(date => getDay(date) !== 5); // Exclude Fridays
    
    // Create table headers
    const headers: any[] = [
      { content: 'SL No.', rowSpan: 2 },
      { content: 'ID#', rowSpan: 2 },
      { content: 'Student Name', rowSpan: 2 },
      { content: 'Class', rowSpan: 2 },
      { content: 'Contact No', rowSpan: 2 },
    ];
    
    // Add date headers
    dates.forEach(date => {
      headers.push({
        content: `${format(date, 'dd/MMM/yy')}\n${DAYS[getDay(date)]}`,
        colSpan: 2,
      });
    });
    
    // AM/PM row
    const amPmRow: any[] = ['', '', '', '', ''];
    dates.forEach(() => {
      amPmRow.push('AM', 'PM');
    });
    
    // Student data rows
    const dataRows = students.map((student, index) => {
      const row = [
        index + 1,
        student.enrollmentNo,
        student.studentName,
        student.class,
        student.contactNo,
      ];
      
      // Add empty cells for attendance marking
      dates.forEach(() => {
        row.push('', ''); // AM and PM columns
      });
      
      return row;
    });
    
    // Add empty rows for manual entries
    const emptyRowsNeeded = Math.max(0, 40 - students.length);
    for (let i = 0; i < emptyRowsNeeded; i++) {
      const emptyRow = [students.length + i + 1, '', '', '', ''];
      dates.forEach(() => {
        emptyRow.push('', '');
      });
      dataRows.push(emptyRow);
    }
    
    // Summary rows
    const summaryRows = [
      ['Student\'s Present', '*', '*', '*', '*', ...Array(dates.length * 2).fill('*')],
      ['Staff Present', '', '', '', '', ...Array(dates.length * 2).fill('')],
      ['Total Present', '', '', '', '', ...Array(dates.length * 2).fill('')],
      ['Incharge\'s Initial', '', '', '', '', ...Array(dates.length * 2).fill('')],
      ['Verified By', '', '', '', '', ...Array(dates.length * 2).fill('')],
    ];
    
    // Generate table
    autoTable(doc, {
      startY: yPos + 4,
      head: [headers, amPmRow],
      body: [...dataRows, ...summaryRows],
      theme: 'grid',
      styles: {
        fontSize: 7,
        cellPadding: 1,
        lineColor: [0, 0, 0],
        lineWidth: 0.1,
      },
      headStyles: {
        fillColor: [255, 255, 255],
        textColor: [0, 0, 0],
        fontStyle: 'bold',
        halign: 'center',
        valign: 'middle',
      },
      columnStyles: {
        0: { cellWidth: 10, halign: 'center' },
        1: { cellWidth: 18, halign: 'center' },
        2: { cellWidth: 40 },
        3: { cellWidth: 12, halign: 'center' },
        4: { cellWidth: 25, halign: 'center' },
      },
      didDrawPage: (data) => {
        // Footer
        doc.setFontSize(8);
        doc.setFont('helvetica', 'italic');
        doc.text(
          'Generated by SIS Transport Management System',
          pageWidth / 2,
          pageHeight - 10,
          { align: 'center' }
        );
      },
    });
    
    return doc;
  }

  // ==================== ROUTE SHEET ====================
  
  static generateRouteSheet(routeData: RouteSheetData): jsPDF {
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Header
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('SHANTINIKETAN INDIAN SCHOOL', pageWidth / 2, 20, { align: 'center' });
    
    doc.setFontSize(14);
    doc.text('BUS ROUTE SHEET', pageWidth / 2, 28, { align: 'center' });
    
    // Bus Details Box
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    const leftMargin = 15;
    let yPos = 40;
    
    // Draw box
    doc.rect(leftMargin, yPos - 5, pageWidth - 30, 40);
    
    doc.setFont('helvetica', 'bold');
    doc.text(`Bus Number: ${routeData.busNumber}`, leftMargin + 5, yPos);
    doc.text(`Shift: ${routeData.shift}`, pageWidth - 30, yPos, { align: 'right' });
    
    yPos += 7;
    doc.setFont('helvetica', 'normal');
    doc.text(`Route: ${routeData.routeName} (${routeData.routeNumber})`, leftMargin + 5, yPos);
    
    yPos += 7;
    doc.text(`Driver: ${routeData.driverName} (${routeData.driverContact})`, leftMargin + 5, yPos);
    
    yPos += 7;
    doc.text(`Conductor: ${routeData.conductorName} (${routeData.conductorContact})`, leftMargin + 5, yPos);
    
    if (routeData.teacherAssigned) {
      yPos += 7;
      doc.text(`Teacher Assigned: ${routeData.teacherAssigned}`, leftMargin + 5, yPos);
    }
    
    yPos += 7;
    doc.setFont('helvetica', 'bold');
    const utilizationPercent = ((routeData.currentOccupancy / routeData.capacity) * 100).toFixed(1);
    doc.text(
      `Capacity: ${routeData.currentOccupancy} / ${routeData.capacity} (${utilizationPercent}%)`,
      leftMargin + 5,
      yPos
    );
    
    // Students Table
    yPos += 12;
    
    const tableHeaders = [
      ['SL No.', 'Enrollment No.', 'Student Name', 'Class', 'Stop Name', 'Contact No.']
    ];
    
    const tableData = routeData.students.map((student, index) => [
      index + 1,
      student.enrollmentNo,
      student.name,
      student.class,
      student.stopName,
      student.contactNo,
    ]);
    
    autoTable(doc, {
      startY: yPos,
      head: tableHeaders,
      body: tableData,
      theme: 'grid',
      styles: {
        fontSize: 9,
        cellPadding: 3,
      },
      headStyles: {
        fillColor: [66, 139, 202],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
      },
      columnStyles: {
        0: { cellWidth: 15, halign: 'center' },
        1: { cellWidth: 25, halign: 'center' },
        2: { cellWidth: 50 },
        3: { cellWidth: 20, halign: 'center' },
        4: { cellWidth: 35 },
        5: { cellWidth: 25, halign: 'center' },
      },
      didDrawPage: (data) => {
        // Footer
        const pageHeight = doc.internal.pageSize.getHeight();
        doc.setFontSize(8);
        doc.setFont('helvetica', 'italic');
        doc.text(
          `Generated on: ${format(new Date(), 'dd-MM-yyyy HH:mm')}`,
          pageWidth / 2,
          pageHeight - 10,
          { align: 'center' }
        );
      },
    });
    
    return doc;
  }

  // ==================== EVENT ROUTE SHEET ====================
  
  static generateEventRouteSheet(eventData: EventRouteSheet): jsPDF {
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Header
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('SHANTINIKETAN INDIAN SCHOOL', pageWidth / 2, 20, { align: 'center' });
    
    doc.setFontSize(14);
    doc.text('EVENT TRANSPORT ARRANGEMENT', pageWidth / 2, 28, { align: 'center' });
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text(`Event: ${eventData.eventName}`, pageWidth / 2, 36, { align: 'center' });
    doc.text(`Date: ${format(new Date(eventData.eventDate), 'dd MMMM yyyy')}`, pageWidth / 2, 43, { align: 'center' });
    
    let yPos = 55;
    
    // Generate a page for each bus
    eventData.buses.forEach((bus, busIndex) => {
      if (busIndex > 0) {
        doc.addPage();
        yPos = 20;
      }
      
      const leftMargin = 15;
      
      // Bus Details Box
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.rect(leftMargin, yPos - 5, pageWidth - 30, 25);
      
      doc.text(`Bus Number: ${bus.busNumber}`, leftMargin + 5, yPos);
      yPos += 7;
      
      doc.setFont('helvetica', 'normal');
      doc.text(`Driver: ${bus.driverName}`, leftMargin + 5, yPos);
      yPos += 7;
      
      doc.text(`Conductor: ${bus.conductorName}`, leftMargin + 5, yPos);
      
      if (bus.teacherAssigned) {
        yPos += 7;
        doc.text(`Teacher In-charge: ${bus.teacherAssigned}`, leftMargin + 5, yPos);
      }
      
      yPos += 12;
      
      // Students Table
      const tableHeaders = [
        ['SL No.', 'Enrollment No.', 'Name', 'Class', 'Stop/Area', 'Contact No.']
      ];
      
      const tableData = bus.students.map((student, index) => [
        index + 1,
        student.enrollmentNo,
        student.name,
        student.class,
        student.stopName || '-',
        student.contactNo,
      ]);
      
      autoTable(doc, {
        startY: yPos,
        head: tableHeaders,
        body: tableData,
        theme: 'grid',
        styles: {
          fontSize: 9,
          cellPadding: 3,
        },
        headStyles: {
          fillColor: [231, 76, 60],
          textColor: [255, 255, 255],
          fontStyle: 'bold',
        },
        columnStyles: {
          0: { cellWidth: 15, halign: 'center' },
          1: { cellWidth: 25, halign: 'center' },
          2: { cellWidth: 50 },
          3: { cellWidth: 20, halign: 'center' },
          4: { cellWidth: 30 },
          5: { cellWidth: 25, halign: 'center' },
        },
        didDrawPage: (data) => {
          // Footer
          const pageHeight = doc.internal.pageSize.getHeight();
          doc.setFontSize(8);
          doc.setFont('helvetica', 'italic');
          doc.text(
            `Page ${busIndex + 1} of ${eventData.buses.length}`,
            pageWidth / 2,
            pageHeight - 10,
            { align: 'center' }
          );
        },
      });
      
      yPos = (doc as any).lastAutoTable.finalY + 15;
      
      // Signature section
      if (yPos < doc.internal.pageSize.getHeight() - 40) {
        doc.setFontSize(10);
        doc.text('Verified By: ___________________', leftMargin + 5, yPos);
        doc.text('Date: _______________', pageWidth - 60, yPos);
      }
    });
    
    return doc;
  }

  // ==================== ANNEXURE LISTS ====================
  
  static generateAnnexureList(
    title: string,
    shift: string,
    students: any[]
  ): jsPDF {
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Header
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('SHANTINIKETAN INDIAN SCHOOL', pageWidth / 2, 20, { align: 'center' });
    
    doc.setFontSize(14);
    doc.text(title, pageWidth / 2, 28, { align: 'center' });
    
    doc.setFontSize(12);
    doc.text(`Shift: ${shift}`, pageWidth / 2, 36, { align: 'center' });
    
    // Students Table
    const tableHeaders = [
      ['SL No.', 'Enrollment No.', 'Name', 'Class', 'Contact No.', 'Transport Status']
    ];
    
    const tableData = students.map((student, index) => [
      index + 1,
      student.enrollmentNo,
      student.name,
      student.class,
      student.contactNo1,
      student.transportStatus || 'Not Using Transport',
    ]);
    
    autoTable(doc, {
      startY: 45,
      head: tableHeaders,
      body: tableData,
      theme: 'grid',
      styles: {
        fontSize: 9,
        cellPadding: 3,
      },
      headStyles: {
        fillColor: [52, 152, 219],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
      },
      columnStyles: {
        0: { cellWidth: 15, halign: 'center' },
        1: { cellWidth: 25, halign: 'center' },
        2: { cellWidth: 60 },
        3: { cellWidth: 20, halign: 'center' },
        4: { cellWidth: 25, halign: 'center' },
        5: { cellWidth: 30, halign: 'center' },
      },
      didDrawPage: (data) => {
        // Footer
        const pageHeight = doc.internal.pageSize.getHeight();
        doc.setFontSize(8);
        doc.setFont('helvetica', 'italic');
        
        const pageNumber = (doc as any).internal.getNumberOfPages();
        doc.text(
          `Page ${data.pageNumber} | Total Students: ${students.length}`,
          pageWidth / 2,
          pageHeight - 10,
          { align: 'center' }
        );
      },
    });
    
    return doc;
  }

  // ==================== UTILITY METHODS ====================
  
  static savePDF(doc: jsPDF, filename: string): void {
    doc.save(filename);
  }

  static getPDFBlob(doc: jsPDF): Blob {
    return doc.output('blob');
  }

  static getPDFDataUri(doc: jsPDF): string {
    return doc.output('datauristring');
  }
}
